### ISSUE TITLE
"Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by tolg** [epayet/simple-restful#2]
When I post or put some data to the api server, I receive a 500 error with "Cannot read property 'name' of undefined". But the operation is worked.

**Comment by epayet** [comment]
Hi @tolg.

Sorry I didn't come back to you earlier. I will have to get my head back into it to tell you exactly what's happening.
I haven't touched the project in a while, but if you like the project, I could give it some love ❤️

**Comment by epayet** [comment]
Hi,

I'm closing this issue as I did a big refactoring for version 2.
If you'd like to give it a go again, it should be much better.

Don't hesitate to open any other issue / PR.
Thanks.
